name: Publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - run: |
          npm install
          npm install -g rollup
          npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - run: |
          git config --global user.email "lam.luongvan2305@gmail.com"
          git config --global user.name "Lam Luong Van"
          npm run build-storybook
          npm run deploy-storybook
